[project]
name = "building-heating"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10,<3.12"

dependencies = [
    "pandas",
    "pandas-stubs~=2.3.3",
    "pysnowflake>=0.1.3",
    "snowflake-snowpark-python",
    "streamlit>=1.52.1",
]
