[snowflake]
[connections.my_example_connection]
account = "FUTDODY-EC44770"
user = "WEIHUA"
password = "XXXXXXXXXXXXXXXXXX"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "TESTDB"
schema = "PUBLIC"